server:
  port: 8080
  ssl:
    enabled: true
    #    key-store: classpath:cert/assignment.p12
    key-store-password: 123456
    key-alias: eureka-server
    key-store-type: PKCS12
    key-store: ../assignment.p12

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: ms-user-service
          uri: https://localhost:8180
          predicates:
            - Path=/user/** , /v3/api-docs/ms-user
        - id: ms-card-service
          uri: https://localhost:8380
          predicates:
            - Path=/card/**,  /v3/api-docs/ms-card
        - id: ms-product-service
          uri: https://localhost:8280
          predicates:
            - Path=/product/** , /v3/api-docs/ms-product
        - id: ms-payment-service
          uri: https://localhost:8480
          predicates:
            - Path=/payment/** , /v3/api-docs/ms-payment
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true