server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      routes:
        - id: ms-user-service
          uri: http://ms-user:8180
          predicates:
            - Path=/user/** , /v3/api-docs/ms-user
        - id: ms-card-service
          uri: http://ms-card:8380
          predicates:
            - Path=/card/**,  /v3/api-docs/ms-card
        - id: ms-product-service
          uri: http://ms-product:8280
          predicates:
            - Path=/product/** , /v3/api-docs/ms-product
        - id: ms-payment-service
          uri: http://ms-payment:8480
          predicates:
            - Path=/payment/** , /v3/api-docs/ms-payment
    discovery:
      enabled: true