server:
  port: 8480
  ssl:
    enabled: true
    #    key-store: classpath:cert/assignment.p12
    key-store-password: 123456
    key-alias: eureka-server
    key-store-type: PKCS12
    key-store: ../assignment.p12

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db
    username: assignment_app
    password: w39irMiSnTaQvuK
  application:
    name: ms-card

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true


