eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    home-page-url: 'https://${eureka.instance.hostName}:${server.port}/'
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: discovery-server

server:
  port: 8761
  ssl:
    enabled: true
#    key-store: classpath:cert/assignment.p12
    key-store-password: 123456
    key-alias: eureka-server
    key-store-type: PKCS12
    key-store: ../assignment.p12


