server:
  port: 8180

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db
    username: assignment_app
    password: w39irMiSnTaQvuK
  application:
    name: ms-user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
