server:
  port: 8180

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment_db
    username: assignment_app
    password: w39irMiSnTaQvuK
  application:
    name: ms-user
